server:
  port: 8080
spring:
#  config:
#    activate:
#      on-profile: local
  redis:
    host: localhost
    port: 6379
  # rabbitMQ 환경설정
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.ctms26socerp.ap-northeast-2.rds.amazonaws.com:3306/ordersystem
    username: admin
    password: 2DxX9irMN5hn0nHO2pZP
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    root: info

jwt:
  expiration: 300
  secretKey: my_token_secret
  expirationRt: 14400
  secretKeyRt: hackerton_secret

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    s3:
      bucket: eunji-file

