name: deploy to ec2 with jar
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 각 작업은 여러 step으로 구성
    steps:
      - name: checkout branch
        uses: actions/checkout@v2

      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: build jar
        working-directory: .
        run: |
          chmod 777 ./gradlew
          ./gradlew bootJar

      - name: copy jar to ec2
        uses: appleboy/scp-action@master
        with:
          host: ec2-52-78-232-231.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
#          pem 키를 통해 해당 인스턴스에 접근
          key: ${{secrets.EC2_PEMKEY}}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu"

      - name: install java and run jar on ec2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-52-78-232-231.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          key: ${{secrets.EC2_PEMKEY}}
          script: |
            if ! type java > /dev/null; then
              sudo apt-get update && sudo apt-get install openjdk-11-jdk -y
            else
              echo "java is already installed"
            fi
            sudo killall java
            nohub java -jar /home/ubuntu/build/libs/*jar \
            --spring.redis.host=${{secrets.REDIS_HOST}} \
            --spring.datasource.url=jdbc:mariadb://${{secrets.DB_HOST}}:3306/order \
            --spring.datasource.username=admin \
            --spring.datasource.password=${{secrets.DB_PW}} \
            --cloud.aws.credentials.access-key=${{S3_KEY}} \
            --cloud.aws.credentials.secret-key=${{S3_SECRET}} > /home/ubuntu/app.log 2>&1 &